### ISSUE TITLE
KL divergence usage 

### ISSUE THREAD

**Issue by SalvatoreRa** [scikit-learn-contrib/qolmat#123]
Hello,

I wanted to test different metrics, but there is something not clear in the documentation and I have not found a working example. For example, the Kullback-Leibler divergence:

```
import pandas as pd
from qolmat.benchmark.metrics import  kl_divergence
# Create two example Pandas Series
series1 = pd.Series([0.1, 0.2, 0.3, 0.4], colu=['A', 'B', 'C', 'D'])
series2 = pd.Series([0.15, 0.25, 0.35, 0.25], index=['A', 'B', 'C', 'D'])

# Assuming df_mask is a DataFrame with the same index as the Series
df_mask = pd.Series([True,True, True, True])

# Compute KL divergence between the two Series
kl_div = kl_divergence(series1, series2, df_mask)

print("KL Divergence:", kl_div)
```

This is returning an error, I am not sure what it is meaning mask in this case

Thank your for your help

**Comment by SalvatoreRa** [comment]
Hi,

it did work, I have just few additional questions. 

- The mask represents where there are NA values? Or it is indicating the indexes that have to be taken into account?
- It works also with np.arrays?

Thank you very much

**Comment by JulienRoussel77** [comment]
Hello, great! The mask represents the values you want to compute the KL divergence on. In our case these are the additional nans which are added during the validation process. If you want to use this function independently of our setting you can adapt the source code, which is rather simple and relies on scipy.stats.entropy.
